### ISSUE TITLE
Update "Namenode Format UUID file" correctly

### ISSUE THREAD

**Issue by kiiranh** [bloomberg/chef-bach#124]
Currently, in bcpc-hadoop::namenode_master recipe [block](https://github.com/bloomberg/chef-bach/blob/master/cookbooks/bcpc-hadoop/recipes/namenode_master.rb#L99-L109) "namenode_txn_fmt" data bag item is only updated on restarting hadoop-hdfs-namenode service. This block should be changed to re-generate that item if the version file differs from that on disk (maybe using a hashing function) -- this would mean HDFS updates would need to happen on the NN running on the `namenode_master.rb` running machine first.

Also, in bcpc-hadoop::journalnode recipe, [this block](https://github.com/bloomberg/chef-bach/blob/master/cookbooks/bcpc-hadoop/recipes/journalnode.rb#L25-L31) is redundant. In the same recipe, [this block](https://github.com/bloomberg/chef-bach/blob/master/cookbooks/bcpc-hadoop/recipes/journalnode.rb#L41-L43) can be made simpler by using chef::bash->cwd to change dir and keeping the code value to just the tar command.
[Resource bash](https://github.com/bloomberg/chef-bach/blob/master/cookbooks/bcpc-hadoop/recipes/journalnode.rb#L39) name can be changed to include the disk# for readability and debugging.

**Comment by cbaenziger** [comment]
Further, [`namenode_master.rb`](https://github.com/bloomberg/chef-bach/blob/1e66d8709d08842e0027508a750ab581f5ad9ec3/cookbooks/bcpc-hadoop/recipes/namenode_master.rb#L104) uses [`make_config`](https://github.com/bloomberg/chef-bach/blob/d77fb5e28ac11e3949bea012408baf67ae4381ae/cookbooks/bcpc/libraries/utils.rb#L58) which does not overwrite the data bag item -- resulting in a tar file without the `jn/Test-Laptop/current/VERSION` file and only the `nn/current/VERSION` file. (For reference, it appears the asymmetry in path names is due to the JN and NN code, not our recipes.)

**Comment by cbaenziger** [comment]
I would prefer to see us create a `make_config!` which overwrites the data bag if present (it may have to be written as a data bag delete and recreate admittedly).
