### ISSUE TITLE
Removing zabbix-work recipe 

### ISSUE THREAD

**Issue by bijugs** [bloomberg/chef-bach#140]
This is related to [chef-bcpc issue #299](https://github.com/bloomberg/chef-bcpc/issues/299).

The ``zabbix-head`` recipe seem to include [zabbix-work](
https://github.com/bloomberg/chef-bach/blob/master/cookbooks/bcpc/recipes/zabbix-head.rb#L139) recipe while we also include both the recipes in the [BCPC-Hadoop-Head role](https://github.com/bloomberg/chef-bach/blob/master/roles/BCPC-Hadoop-Head.json#L12-L13). Can we remove the include in ``zabbix-head`` recipe so that we can avoid installing ``zabbix-agent`` by removing the ``zabbix-work`` recipe from all the roles.

**Comment by amithkanand** [comment]
This is fixed in PR #143

**Comment by amithkanand** [comment]
Removal of `zabbix-agent` removes `zabbix-sender` and that breaks sending data from `graphite` to `zabbix`. Since we have been using building `Zabbix` using source, we should probably move to using [`zabbix debian`](http://repo.zabbix.com/zabbix/2.2/ubuntu/pool/main/z/zabbix/) repository to manage the installation of different packages in a better way.

**Comment by bijugs** [comment]
As per previous comment closing this issue.
