### ISSUE TITLE
Disks need to be wiped after repxe

### ISSUE THREAD

**Issue by kiiranh** [bloomberg/chef-bach#149]
With recent repxe work on a cluster, it was observed that after repxe of a node when you chef it, disk mount fails. One has to fsck or wipe the disks to fix the disk and chef again to mount. Only some nodes have this issue where a disk still has uuid after repxe and poses this problem. With critical data stored on the disks and repxe'ing a node being an operational step, the disk format/mount should be consistent and definitive.

**Comment by kiiranh** [comment]
This could be because during repxe process, we use impi to power off the boxes instead of shutting down the OS first. Need to test this out.

**Comment by cbaenziger** [comment]
This sounds like a dup of #114 and using a modified preseed file.

Today, stock chef-bach does wipe disk headers during a re-PXE using [dd](https://github.com/bloomberg/chef-bach/blob/a4dd35cb670ed14c4688f9f949ea29d8f228522c/cookbooks/bcpc/templates/default/cobbler.bcpc_ubuntu_host.preseed.erb#L25) as this was part of the original bloomberg/chef-bcpc code base to clear the Ceph state-machine held in [GPT GUIDs](https://en.wikipedia.org/wiki/GUID_Partition_Table#Partition_type_GUIDs).

For sites using chef-bach in practice I recommend not leaving your preseed setup to wipe disks as an errant (or intentional) re-PXE would then cause data loss opposed to simply wiping out the OS for an upgrade of binaries.
