### ISSUE TITLE
Hannibal doesn't  support Kerberos

### ISSUE THREAD

**Issue by amithkanand** [bloomberg/chef-bach#182]
Current implementation of `Hannibal` only works with non `kerberized` cluster. In a `kerberized` environment `Hannibal` service can't talk to secure `Hbase`. A thought to fix this is:
- Create a `hannibal` user during installation.
- A `keytab` for this new user will be required
- Logic to renew tickets for `Hannibal` will have to be developed

**Comment by cbaenziger** [comment]
Some issues it would appear with Hannibal are needing to update the [Play WebService API](https://www.playframework.com/documentation/2.3.x/JavaWS) calls to do SPNEGO authentication.

Perhaps, we can set the Hannibal configuration file to accept a keytab and have Hannibal orchestrate the ticket renewals or if we run Hannibal as the HBase user instead of nobody, we may leverage the HBase tickets already present on the machine for now.

Lastly, in sentric/hannibal#19 there is discussion of Hannibal possibly working on a kerberized cluster as well. Perhaps there are some lessons we can take from there.
