### ISSUE TITLE
The mapreduce tarball is not uploaded to HDFS after first cluster role convergence.

### ISSUE THREAD

**Issue by http-418** [bloomberg/chef-bach#342]
In a cluster built using tests/automated_install, map/reduce jobs fail because the mapreduce.tar.gz file is missing from its expected path in HDFS.

If the nodes are re-converged after tests/automated_install, the mapreduce tarball is successfully uploaded, but shouldn't HDFS work after a single C-A-R invocation?

ls output from hdfs:
https://gist.github.com/http-418/2a1cc6b6a98d2e7a8c6c

The output from the failed submission:
https://gist.github.com/http-418/6710c536c3fe6e97fc44

**Comment by cbaenziger** [comment]
Indeed, the desire (and usually design) of Chef-BACH is for a single converge of `cluster-assign-roles.sh` (e.g. a converged of `role[Basic]` and the role as specified in `cluster.txt`) to be sufficient for one to use the cluster.

However, it looks like [`resource_manager.rb:59`](https://github.com/bloomberg/chef-bach/blob/45695a79a3eb73ff294ea6ada3ec0f4283bd74aa/cookbooks/bcpc-hadoop/recipes/resource_manager.rb#L59) is the culprit as when the resource manager recipe converges we do not yet have HDFS available for data operations (only metadata operations).

**Comment by cbaenziger** [comment]
One idea, we could move [`setup-mapreduce-app`](https://github.com/bloomberg/chef-bach/blob/45695a79a3eb73ff294ea6ada3ec0f4283bd74aa/cookbooks/bcpc-hadoop/recipes/resource_manager.rb#L49-L61) to the worker node role. I believe we have seen on a few hardware clusters where workers chef in impressively deterministic time and HDFS operations do fail out we need to handle collisions in HDFS better since nodes then error racing to create a file.
