### ISSUE TITLE
Hadoop Kerberos mapping is insecure

### ISSUE THREAD

**Issue by mlongob** [bloomberg/chef-bach#382]
This:
https://github.com/bloomberg/chef-bach/blob/master/cookbooks/bcpc-hadoop/templates/default/hdp_core-site.xml.erb#L95-L107

would allow any principal from any domain to be authenticated on the cluster as the local principal.

**Comment by pu239ppy** [comment]
This can be fixed either
1. defining a principal per cluster (i.e. hbase-cluster1 which then becomes hbase-cluster1@host{1,2,3} etc)
2. using auth to local rules in order to filter out service principals not belonging in the cluster
3. a combination of 1 and 2

Since Kerberos only provides authentication, these can be used as authorization controls.  In addition an identity management system can be used to ensure that no one can reserve hbase@anything in enterprise, however 1,2, and 3 are easier to implement and give cluster administrators more flexibility and control.

Both of the above can be extended to amalgamation of clusters such as resilient cluster pairs
