### ISSUE TITLE
Unable to upload cookbooks after versioning them

### ISSUE THREAD

**Issue by amithkanand** [bloomberg/chef-bach#569]
I am getting following error while running `knife cookbook upload -a`
```
vagrant@bcpc-bootstrap:~/chef-bcpc$ knife cookbook upload -a
ERROR: Chef::Exceptions::InvalidCookbookVersion: '1.0.0-SNAPSHOT' does not match 'x.y.z' or 'x.y'
```

The version number doesn't seem to be in line with what `Chef` is expecting.

**Comment by http-418** [comment]
Chef won't allow us to use "-SNAPSHOT" for ephemeral versions, so for now we are just using the nonsense version "0.1.0" for the master branch.

This gives us some "belt and suspenders" protections against accidental local changes:
- Seeing "0.1.0" on an active cluster should be very alarming.
- The environment file should have a cookbook version pin that forbids the use of any "0.1.0" cookbook even if they are accidentally uploaded.
- Running a mixed set of release and non-release cookbooks should be impossible because the "0.1.0" versions from master will not satisfy dependencies.
