### ISSUE TITLE
VMs stuck in UEFI boot after restart

### ISSUE THREAD

**Issue by amithkanand** [bloomberg/chef-bach#673]
Once the VM cluster is built and running successfully, restarting a VM fails to boot properly and is stuck in `EFI` boot menu. Currently @leochen4891 and I are facing this issue.

**Comment by leochen4891** [comment]
![vm1_start](https://cloud.githubusercontent.com/assets/3683228/18719218/720caf52-7ff4-11e6-8011-28c563836afa.PNG)

**Comment by http-418** [comment]
That's the UEFI shell.  When Virtualbox fails to find a bootable medium in UEFI mode, it dumps you into the shell.  The shell is not particularly useful for troubleshooting.

The big question is why your root disk is not bootable.

Clearly it was bootable at least once, or else you would never have been able to log into the VM in order to reboot it. 

1. Are there filesystems on the root disk?
2. Is grub installed?  Is there a grubx64 EFI application in the FAT fs on the root volume?
3. Did the BACH disk recipe accidentally wipe your root disk?

**Comment by http-418** [comment]
I did a fresh build and deliberately halted the process before allowing the VMs to be chef'd.

One of my three VMs failed to boot in the fashion Lei and Amit describe.  Reinstalling the OS with `cobbler system edit --name=bcpc-vm1 --netboot-enabled=1` fixed the problem.

I have no idea what would cause a system to intermittently boot.  This is the default configuration from Canonical.

**Comment by http-418** [comment]
Unfortunately, since I interrupted the process, I didn't get the snapshots of the finished machines.  The next troubleshooting steps involve those snapshots:

1. Verify that the boot problem recurs after restoring to a known-good snapshot and rebooting
2. examine the root, boot,  and EFI system volumes with a rescue medium.  A grubx64.efi should be installed to the EFI system volume etc.
3. lastly, get a step-through debugger working on Virtualbox.  The UEFI firmware is a userspace process and we should be able to examine what it's doing byte-by-byte.

I don't see myself tackling this problem this month.

**Comment by aespinosa** [comment]
Current workaround for now is to revert to BIOS boots
