### ISSUE TITLE
chef-vault cookbook missing ChefVaultCookbook::Provider

### ISSUE THREAD

**Issue by pu239ppy** [bloomberg/chef-bach#873]
I found that this error happens when trying to build master

````
================================================================================
  Recipe Compile Error in /var/chef/cache/cookbooks/bcpc/recipes/cobbler.rb
  ================================================================================

  NameError
  ---------
  uninitialized constant ChefVaultCookbook::Provider

  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/bcpc/recipes/cobbler.rb:58:in `block in from_file'
    /var/chef/cache/cookbooks/bcpc/recipes/cobbler.rb:53:in `from_file'

  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/bcpc/recipes/cobbler.rb:

   51:  root_password_salted = root_password.crypt('$6$' + rand(36**8).to_s(36))
   52:
   53:  chef_vault_secret 'cobbler' do
   54:    #
   55:    # For some reason, we are compelled to specify a provider.
   56:    # This will probably break if we ever move to chef-vault cookbook 2.x
   57:    #
   58>>   provider ChefVaultCookbook::Provider::ChefVaultSecret
   59:
   60:    data_bag 'os'
   61:    raw_data('web-password' => web_password,
   62:             'root-password' => root_password,
   63:             'root-password-salted' => root_password_salted)
   64:    admins node[:fqdn]
   65:    search '*:*'
   66:    action :create_if_missing
   67:  end
````

I fixed up *cookbooks/bcpc/metadata.rb* to require a specific version of chef-vault cookbook as opposed to v3.x that gets pulled in 

````
-depends 'chef-vault'
+depends 'chef-vault', '=1.3.3'
````

Testing fix now

**Comment by vt0r** [comment]
What happens if the `provider` parameter just gets removed? Assuming the cookbook got upgraded, we should be able to just remove that line from the resource, right?

**Comment by http-418** [comment]
I don't know why the resource doesn't work without specifying a provider.  You can try removing the `provider` line, or updating the provider to match the class name in a current version of the cookbook.

**Comment by http-418** [comment]
I also particularly enjoy line 56:
```
   56:    # This will probably break if we ever move to chef-vault cookbook 2.x
```

**Comment by cbaenziger** [comment]
Cross posting from #876 :
Since we use a modern version of Chef (>12.9) we should move to using Chef-Vault's custom provider likely (which removed the ancient provider we were using): [chef-cookbooks/chef-vault #58 change](https://github.com/chef-cookbooks/chef-vault/pull/58/files#diff-fb6cda3ef49a27a1c9f4ecdcf032c520L18)

**Comment by vt0r** [comment]
So I've found something interesting when debugging this issue further:

1. If upgrading to the 2.x versions of the `chef-vault` cookbook, the provider line is entirely unnecessary (along with Chef 12), and removing it resolves this issue.
2. If upgrading to the 3.0.0 version, however, a new issue comes up involving an undefined method on `get_clients`, which is [defined here](https://github.com/chef-cookbooks/chef-vault/blob/master/resources/secret.rb#L17).

Number 2 may actually be a simple fix, since the most likely reason for this error was using the 2.9.1 version of the gem while using the 3.0.0 version of the cookbook. We'll need to update the semantic version requirement for the gem in both OS and repository configurations, then we should be able to remove the version constraint from `cookbooks/bcpc/metadata.rb` added in #882.

**Comment by pu239ppy** [comment]
Strange as it still exists in 3.x
https://github.com/chef/chef-vault/blob/895fb67e278bb86c732157abdd1c2eed3fb436a7/lib/chef-vault/item.rb#L119

**Comment by vt0r** [comment]
This is worked around in #882 by pinning a 2.x version of the `chef-vault` cookbook. Keeping this issue open to track the progress of upgrading to the latest gem and cookbook versions.
